{
 "title": "EcoFlow",
 "description": "EcoFlow dashboard",
 "tags": [
  "ecoflow",
  "prometheus",
  "electricity",
  "IoT"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(ecoflow_online, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_online or ecoflow_cms_bms_run_state"
    }
   ]
  },
  {
   "title": "Inverter IN Watts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_pow_in_sum_w" }
   ]
  },
  {
   "title": "Charging Remaining Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_bms_chg_rem_time" }
   ]
  },
  {
   "title": "Is light?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_chg_dsg_state" }
   ]
  },
  {
   "title": "Full Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ecoflow_bms_design_cap * 51.2) / 1000"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_bms_batt_vol" }
   ]
  },
  {
   "title": "MIN Cell Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_min_cell_vol or ecoflow_bms_bms_status_min_cell_vol or ecoflow_bms_min_cell_vol"
    }
   ]
  },
  {
   "title": "MAX Cell Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_max_cell_vol or ecoflow_bms_bms_status_max_cell_vol or ecoflow_max_cell_vol"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_batt_soc or ecoflow_soc"
    }
   ]
  },
  {
   "title": "Inverter OUT Watts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ecoflow_pow_get_ac_hv_out * -1) or (ecoflow_output_watts * -1)"
    }
   ]
  },
  {
   "title": "Discharging Remaining Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_bms_dsg_rem_time" }
   ]
  },
  {
   "title": "Cycles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_cycles" }
   ]
  },
  {
   "title": "Remain Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ecoflow_remain_cap * 51.2) / 1000"
    }
   ]
  },
  {
   "title": "Inverter Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_temp" }
   ]
  },
  {
   "title": "MIN Cell Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_min_cell_temp or ecoflow_bms_bms_status_min_cell_temp or ecoflow_bms_min_cell_temp"
    }
   ]
  },
  {
   "title": "MAX Cell Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_max_cell_temp or ecoflow_bms_bms_status_max_cell_temp or ecoflow_max_cell_temp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecoflow_chg_dsg_state" }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ecoflow_bms_batt_soc or ecoflow_soc or ecoflow",
     "legendFormat": "Battery Level"
    }
   ]
  },
  {
   "title": "I/O Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_pow_in_sum_w or ecoflow_input_watts",
     "legendFormat": "Input Watts"
    },
    {
     "expr": "(ecoflow_pow_get_ac_hv_out * -1) or (ecoflow_output_watts * -1)",
     "legendFormat": "Output Watts"
    }
   ]
  },
  {
   "title": "Remaining Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    { "expr": "ecoflow_cms_chg_rem_time", "legendFormat": "Charging Remain Time" },
    { "expr": "ecoflow_bms_dsg_rem_time", "legendFormat": "Discharging Remain Time" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "ecoflow_temp", "legendFormat": "Inverter" },
    { "expr": "ecoflow_pd_car_temp != 0", "legendFormat": "PD Car" },
    { "expr": "ecoflow_temp", "legendFormat": "BMS" },
    { "expr": "ecoflow_max_cell_temp", "legendFormat": "Max Cell" },
    { "expr": "ecoflow_bms_min_cell_temp", "legendFormat": "Min Cell" },
    { "expr": "ecoflow_max_mos_temp", "legendFormat": "Max MOS" },
    { "expr": "ecoflow_min_mos_temp", "legendFormat": "Min MOS" }
   ]
  },
  {
   "title": "USB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "ecoflow_pd_usb1_watts", "legendFormat": "USB" },
    { "expr": "ecoflow_pd_typec1_watts", "legendFormat": "TypeC" }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_vol or ecoflow_bms_bms_status_vol",
     "legendFormat": "BMS"
    },
    {
     "expr": "ecoflow_bms_master_min_cell_vol or ecoflow_bms_bms_status_min_cell_vol or ecoflow_bms_min_cell_vol",
     "legendFormat": "MIN Cell"
    },
    {
     "expr": "ecoflow_bms_master_max_cell_vol or ecoflow_bms_bms_status_max_cell_vol or ecoflow_max_cell_vol",
     "legendFormat": "MAX Cell"
    }
   ]
  },
  {
   "title": "MPPT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Solar power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      { "expr": "ecoflow_mppt_in_watts/10", "legendFormat": "Watts in" },
      {
       "expr": "ecoflow_mppt_in_vol * ecoflow_mppt_in_amp / 1000",
       "legendFormat": "Watts on panel"
      }
     ]
    },
    {
     "title": "Solar voltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      { "expr": "ecoflow_mppt_in_vol/10", "legendFormat": "Volts in" }
     ]
    },
    {
     "title": "Solar current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      { "expr": "ecoflow_mppt_in_amp/100", "legendFormat": "Amp in" }
     ]
    },
    {
     "title": "Battery Managemant System Power Balance ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      { "expr": "ecoflow_bms_master_amp/1000", "legendFormat": "Amp in" }
     ]
    },
    {
     "title": "Solar power",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time(ecoflow_mppt_in_watts[$__range]) / (count_over_time(ecoflow_mppt_in_watts[1m]) * 60) / 10",
       "legendFormat": "Battery charged"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_out_watts[$__range]) / (count_over_time(ecoflow_mppt_out_watts[1m]) * 60) / 10",
       "legendFormat": "Collected"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_in_watts[24h]) / (count_over_time(ecoflow_mppt_in_watts[1m]) * 60) / 10",
       "legendFormat": "Battery charged (24h)"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_out_watts[24h]) / (count_over_time(ecoflow_mppt_out_watts[1m]) * 60) / 10",
       "legendFormat": "Collected (24h)"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_in_watts[7d]) / (count_over_time(ecoflow_mppt_in_watts[1m]) * 60) / 10",
       "legendFormat": "Battery charged (7d)"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_out_watts[7d]) / (count_over_time(ecoflow_mppt_out_watts[1m]) * 60) / 10",
       "legendFormat": "Collected (7d)"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_in_watts[30d]) / (count_over_time(ecoflow_mppt_in_watts[1m]) * 60) / 10",
       "legendFormat": "Battery charged (30d)"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_out_watts[30d]) / (count_over_time(ecoflow_mppt_out_watts[1m]) * 60) / 10",
       "legendFormat": "Collected (30d)"
      }
     ]
    },
    {
     "title": "Battery Energy Balance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "ecoflow_bms_master_vol/1000 * ecoflow_bms_master_amp/1000",
       "legendFormat": "Master BMS"
      },
      {
       "expr": "ecoflow_mppt_in_vol * ecoflow_mppt_in_amp / 1000",
       "legendFormat": "Solar"
      }
     ]
    }
   ]
  },
  { "title": "MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "MQTT Messages Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "m/s" } },
   "targets": [
    {
     "expr": "rate(ecoflow_mqtt_messages_receive_total[1m])",
     "legendFormat": "MQTT Messages"
    }
   ]
  }
 ]
}